{
  "hash": "ea313b1450c202d677fb6468f41c7944",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nauthor: jshn9515\ndate: 2026-05-13\ndate-modified: 2026-05-13\nopen-graph:\n  title: ch11.3-positional-embedding\n  description: \"11.3 Class Token and Positional Embedding: Representing the Whole Image\"\ntitle: \"11.3 Class Token and Positional Embedding: Letting a Sequence Represent the Whole Image\"\norder: 3\n---\n\nIn the previous section, we converted the image from the original tensor\n\n$$\n(B, C, H, W)\n$$\n\ninto a patch token sequence\n\n$$\n(B, N, D)\n$$\n\nwhere $N$ is the number of patches, and $D$ is the embedding dimension of each token.\n\nAt this point, an image can already be viewed as a sequence of visual tokens and can be fed into a Transformer Encoder.\n\nHowever, this is still not the complete input of ViT. We still have two unresolved problems.\n\nThe first problem is: if we want to do image classification, which token should finally represent the whole image? A patch token itself represents a local image block, while a classification task needs a semantic representation of the whole image.\n\nThe second problem is: Transformer itself does not know where each patch comes from in the image. After patch embedding cuts the image into a sequence, if no extra positional information is added, it is hard for the model to distinguish whether a patch comes from the upper-left corner or the lower-right corner.\n\nTherefore, before feeding patch tokens into the Transformer Encoder, ViT does two more things:\n\n1. Add a **class token** at the beginning of the sequence, used to aggregate information from the whole image;\n2. Add **positional embedding** to each token, used to tell the model the position information of the token.\n\nIn this section, we discuss these two designs.\n\n::: {#428b9da4 .cell execution_count=1}\n``` {.python .cell-code}\nimport torch\nimport torch.nn as nn\nimport torch.nn.functional as F\nfrom dnnl.models.vit import ViTConvPatchEmbedding\nfrom torch import Tensor\n\nprint('PyTorch version:', torch.__version__)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPyTorch version: 2.12.0+xpu\n```\n:::\n:::\n\n\n## 11.3.1 Patch Tokens Still Cannot Directly Represent the Whole Image\n\nAfter patch embedding, an image becomes a patch sequence:\n\n$$\nX = [x_1, x_2, \\dots, x_N]\n$$\n\nwhere each $x_i \\in \\mathbb{R}^D$ represents an image patch.\n\nIf a Transformer Encoder is attached afterward, the output is still a sequence:\n\n$$\nH = [h_1, h_2, \\dots, h_N]\n$$\n\nHere each $h_i$ is the contextual representation of the corresponding patch. It no longer contains only the information of the $i$-th patch itself, but has fused information from other patches through self-attention.\n\nBut for image classification, what we finally need is a vector representation of the whole image, not $N$ patch vectors. In other words, we need to obtain an image representation of shape `(B, D)` from the output of shape `(B, N, D)`.\n\nA very natural approach is to average-pool all patch tokens:\n\n$$\nh_\\mathrm{avg} = \\frac{1}{N}\\sum_{i=1}^N h_i\n$$\n\nThis is certainly feasible. In fact, many later visual Transformer variants also use average pooling or similar aggregation methods.\n\nBut the original ViT adopts another design: it adds a special learnable token before the patch tokens, called the **class token**, often written as `[CLS]`.\n\n## 11.3.2 Class Token: Letting One Token Represent the Whole Image\n\nThe idea of the class token comes from Transformer models such as BERT. In text classification, the model adds a special token, such as `[CLS]`, at the beginning of the input sequence. After Transformer encoding, the output representation of this token is used as the representation of the whole sequence. ViT borrows this idea.\n\nSuppose the patch token sequence is:\n\n$$\n[x_1, x_2, \\dots, x_N]\n$$\n\nViT adds a learnable vector $x_\\mathrm{cls}$ in front of it:\n\n$$\nX = [x_\\mathrm{cls}, x_1, x_2, \\dots, x_N]\n$$\n\nIn this way, the sequence length changes from $N$ to $N + 1$.\n\nThis class token is initially just an ordinary learnable parameter. It does not correspond to any patch in the image, nor does it come from the input image. Its role is to interact with all patch tokens through self-attention in the Transformer Encoder.\n\nAfter multiple Transformer Encoder layers, the output representation of the class token can be regarded as the aggregated information of the whole image:\n\n$$\nh_\\mathrm{cls} = H[:, 0, :]\n$$\n\nThen this vector is fed into the classification head to obtain image classification logits:\n\n$$\n\\mathrm{logits} = h_\\mathrm{cls} W + b\n$$\n\nIntuitively, the class token is like a global position. It does not represent a local image block, but is specially used to collect information from all patch tokens and finally form the representation of the whole image.\n\n## 11.3.3 PyTorch Implementation of Class Token\n\nIn implementation, the class token is usually a learnable parameter with shape `(1, 1, embed_dim)`:\n\n::: {#6b0dde2f .cell execution_count=2}\n``` {.python .cell-code}\nclass ViTAddClassToken(nn.Module):\n    def __init__(self, embed_dim: int):\n        super().__init__()\n        cls_token = torch.zeros(1, 1, embed_dim)\n        self.cls_token = nn.Parameter(cls_token)\n        nn.init.trunc_normal_(self.cls_token, std=0.02)\n\n    def forward(self, x: Tensor) -> Tensor:\n        cls_token = self.cls_token.expand(x.size(0), -1, -1)\n        x = torch.concat([cls_token, x], dim=1)\n        return x\n```\n:::\n\n\nThere are two details worth noting here.\n\nThe first detail is that the shape of `cls_token` is `(1, 1, D)`, not `(B, 1, D)`. Because it is a model parameter, we should not store a separate copy for each batch. During the actual forward pass, we use `expand` to expand it to the current batch size:\n\n```python\ncls_token = self.cls_token.expand(batch_size, -1, -1)\n```\n\nThe second detail is that `expand` does not really copy the parameter data. It only creates a broadcasted view. In this way, all samples use the same learnable class token, but in the computation graph it is updated together according to the gradients from all samples in the batch.\n\nLet us test the shape change:\n\n::: {#f7efb5ab .cell execution_count=3}\n``` {.python .cell-code}\nnum_patches = 16\nembed_dim = 64\n\nx = torch.randn(2, num_patches, embed_dim)\ncls_layer = ViTAddClassToken(embed_dim)\nout = cls_layer(x)\n\nprint('Input shape:', x.shape)\nprint('Output shape:', out.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nInput shape: torch.Size([2, 16, 64])\nOutput shape: torch.Size([2, 17, 64])\n```\n:::\n:::\n\n\nThe input shape is `(B, N, D)`, and the output shape becomes `(B, N + 1, D)`. The extra first token is the class token.\n\n## 11.3.4  Positional Embedding: Letting the Model Know Token Positions\n\nAfter adding the class token, the sequence can already represent the whole image. But we still have another problem: where is the positional information of patch tokens?\n\nPatch embedding gives us a sequence of vectors:\n\n$$\n[x_1, x_2, \\dots, x_N]\n$$\n\nAlthough we usually arrange patches from left to right and from top to bottom when flattening them, self-attention itself does not naturally understand the meaning of this order.\n\nThis is the same problem as in text Transformers. When self-attention computes, it mainly looks at similarity among token vectors. Without additional positional information, it does not know whether a token is at the first position or the tenth position.\n\nFor images, position is even more important. A patch in the upper-left corner and a patch in the lower-right corner may have completely different semantics. For example, the sky is usually in the upper part of an image, and grass is usually in the lower part; eyes, nose, and mouth in a face also have relatively stable spatial relationships. If the model has no idea about patch positions, it is hard to use these spatial structures.\n\nTherefore, ViT adds a learnable position vector to each token:\n\n$$\nZ = X + P\n$$\n\nwhere $X \\in \\mathbb{R}^{B \\times (N+1) \\times D}$ is the sequence after adding the class token, and $P \\in \\mathbb{R}^{1 \\times (N+1) \\times D}$ is the position embedding.\n\nNote that the number of positions here is $N + 1$, because besides the $N$ patch tokens, the class token also needs its own position embedding.\n\n## 11.3.5 PyTorch Implementation of Positional Embedding\n\nThe original ViT uses learnable absolute positional embeddings. That is, the model directly learns a parameter matrix:\n\n$$\nP = [p_\\mathrm{cls}, p_1, p_2, \\dots, p_N]\n$$\n\nwhere $p_\\mathrm{cls}$ is the positional embedding of the class token, and $p_i$ is the positional embedding of the $i$-th patch position.\n\nThen it is added to the token embeddings:\n\n$$\nZ = X + P\n$$\n\nThe implementation is very simple:\n\n::: {#f59ef720 .cell execution_count=4}\n``` {.python .cell-code}\nclass ViTPositionalEmbedding(nn.Module):\n    def __init__(\n        self,\n        embed_dim: int,\n        num_patches: int,\n        use_cls_token: bool = True,\n    ):\n        super().__init__()\n        self.use_cls_token = use_cls_token\n\n        num_tokens = num_patches + int(use_cls_token)\n        pos_embed = torch.zeros(1, num_tokens, embed_dim)\n        self.pos_embed = nn.Parameter(pos_embed)\n        nn.init.trunc_normal_(self.pos_embed, std=0.02)\n\n    def forward(self, x: Tensor) -> Tensor:\n        if x.size(1) != self.pos_embed.size(1):\n            raise AssertionError(\n                f'Expected sequence length {self.pos_embed.size(1)}, '\n                f'but got {x.size(1)}.'\n            )\n        return x + self.pos_embed\n```\n:::\n\n\nTest it:\n\n::: {#025d5e16 .cell execution_count=5}\n``` {.python .cell-code}\nnum_patches = 16\nembed_dim = 64\n\nx = torch.randn(2, num_patches, embed_dim)\nx = ViTAddClassToken(embed_dim)(x)\npos_embed = ViTPositionalEmbedding(\n    num_patches=num_patches,\n    embed_dim=embed_dim,\n    use_cls_token=True,\n)\nout = pos_embed(x)\n\nprint('After class token:', x.shape)\nprint('After positional embedding:', out.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAfter class token: torch.Size([2, 17, 64])\nAfter positional embedding: torch.Size([2, 17, 64])\n```\n:::\n:::\n\n\nWe can see that adding positional embedding does not change the tensor shape. It only adds a position-related offset to the representation of each token.\n\nThat is:\n\n$$\n(B, N+1, D) \\rightarrow (B, N+1, D)\n$$\n\nThe dimensions do not change, but the token representations now contain positional information.\n\n## 11.3.6 The Order of Class Token and Positional Embedding\n\nIn ViT, the common input construction order is:\n\n$$\n\\text{image}\n\\rightarrow\n\\text{patch embedding}\n\\rightarrow\n\\text{append class token}\n\\rightarrow\n\\text{add positional embedding}\n$$\n\nThat is:\n\n$$\n(B, C, H, W)\n\\rightarrow\n(B, N, D)\n\\rightarrow\n(B, N+1, D)\n\\rightarrow\n(B, N+1, D)\n$$\n\nWhy is the class token usually added first, and then positional embedding added afterward?\n\nBecause positional embedding needs to correspond one-to-one to every token in the final input sequence. If positional embedding is first added to patch tokens and then the class token is concatenated, then the class token still needs to handle its own positional embedding separately. It is more direct to concatenate the class token first and then uniformly add a position embedding of length $N+1$.\n\nBelow, we combine the patch embedding from the previous section with the class token and positional embedding discussed in this section to obtain a complete ViT input module.\n\n::: {#7e92d259 .cell execution_count=6}\n``` {.python .cell-code}\nclass ViTEmbedding(nn.Module):\n    def __init__(\n        self,\n        image_size: int = 224,\n        patch_size: int = 16,\n        in_channels: int = 3,\n        embed_dim: int = 768,\n        dropout: float = 0.0,\n    ):\n        super().__init__()\n        self.patch_embed = ViTConvPatchEmbedding(\n            image_size=image_size,\n            patch_size=patch_size,\n            in_channels=in_channels,\n            embed_dim=embed_dim,\n        )\n        self.add_cls_token = ViTAddClassToken(embed_dim)\n        self.pos_embed = ViTPositionalEmbedding(\n            num_patches=self.patch_embed.num_patches,\n            embed_dim=embed_dim,\n            use_cls_token=True,\n        )\n        self.dropout = nn.Dropout(dropout)  # <1>\n\n    def forward(self, x: Tensor) -> Tensor:\n        x = self.patch_embed(x)\n        x = self.add_cls_token(x)\n        x = self.pos_embed(x)\n        x = self.dropout(x)\n        return x\n```\n:::\n\n\n1. The `Dropout` here is optional. The original ViT does not add dropout after the input module, but many later variants add a dropout layer here to increase input randomness and improve model generalization.\n\nTest the shape:\n\n::: {#082d43b3 .cell execution_count=7}\n``` {.python .cell-code}\nvit_embed = ViTEmbedding(\n    image_size=32,\n    patch_size=8,\n    in_channels=3,\n    embed_dim=64,\n)\n\nx = torch.randn(2, 3, 32, 32)\nout = vit_embed(x)\n\nprint('ViT embedding output shape:', out.shape)\nprint('Number of patch tokens:', vit_embed.patch_embed.num_patches)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nViT embedding output shape: torch.Size([2, 17, 64])\nNumber of patch tokens: 16\n```\n:::\n:::\n\n\nHere the image size is $32 \\times 32$, and the patch size is $8 \\times 8$, so each image has 16 patch tokens. After adding the class token, the sequence length becomes 17. Therefore, the output shape is `(B, 17, D)`.\n\n## 11.3.7 Positional Embedding and Two-Dimensional Spatial Structure\n\nAt this point, there may still be one confusing point:\n\n> **The image is originally a two-dimensional grid, but ViT's positional embedding looks one-dimensional. Does this lose the two-dimensional spatial structure?**\n\nThe answer is no. Although ViT uses one-dimensional position embedding, this does not mean it completely discards the two-dimensional positional information of the image. This is because the patch sequence is obtained by flattening the two-dimensional grid in a fixed order.\n\nFor example, a $14 \\times 14$ patch grid is flattened into 196 patch tokens in row-major order. In this way, the $i$-th position in the sequence always corresponds to a fixed patch coordinate in the original image. Therefore, although the shape of positional embedding is $(1, N+1, D)$ and appears to only add position vectors to a one-dimensional sequence, each position vector actually corresponds to a two-dimensional patch position behind the scenes.\n\nHowever, this kind of learnable absolute positional embedding also has a limitation: it is tightly bound to the patch grid size used during training. For example, if the model is trained with $224 \\times 224$ images and $16 \\times 16$ patches, then the patch grid is $14 \\times 14$ and the positional embedding length is 197. If a higher-resolution image is used during inference, such as $384 \\times 384$, the patch grid becomes $24 \\times 24$ and the positional embedding length becomes 577. At this point, the length of the original positional embedding no longer matches.\n\nWhat should we do then?\n\nA common method is to apply two-dimensional interpolation to the patch part of the positional embedding. The positional embedding of the class token is kept separately; the patch positional embedding is first restored into a two-dimensional grid, then interpolated to the new grid size, and finally flattened back into a sequence.\n\nThe concrete steps are:\n\n1. Separate the positional embedding of the class token and the positional embedding of patch tokens from the positional embedding.\n2. Reshape the positional embedding of patch tokens into a two-dimensional grid shape `(1, old_h, old_w, D)`.\n3. Use bilinear interpolation to interpolate the positional embedding from the old grid size to the new grid size `(1, new_h, new_w, D)`.\n4. Reshape the interpolated patch positional embedding back into sequence shape `(1, new_h * new_w, D)`.\n5. Concatenate the positional embedding of the class token and the new patch positional embedding to obtain the new positional embedding.\n\nBelow is a simplified implementation:\n\n::: {#6e100682 .cell execution_count=8}\n``` {.python .cell-code}\ndef interpolate_pos_embedding(\n    pos_embed: Tensor,\n    old_grid_size: tuple[int, int],\n    new_grid_size: tuple[int, int],\n) -> Tensor:\n    cls_pos_embed = pos_embed[:, :1]\n    patch_pos_embed = pos_embed[:, 1:]\n\n    old_h, old_w = old_grid_size\n    new_h, new_w = new_grid_size\n    embed_dim = pos_embed.size(-1)\n\n    patch_pos_embed = patch_pos_embed.reshape(1, old_h, old_w, embed_dim)\n    patch_pos_embed = patch_pos_embed.permute(0, 3, 1, 2)\n    patch_pos_embed = F.interpolate(\n        patch_pos_embed,\n        size=(new_h, new_w),\n        mode='bicubic',\n        align_corners=False,  # <1>\n    )\n    patch_pos_embed = patch_pos_embed.permute(0, 2, 3, 1)\n    patch_pos_embed = patch_pos_embed.reshape(1, new_h * new_w, embed_dim)\n\n    new_embed = torch.concat([cls_pos_embed, patch_pos_embed], dim=1)\n    return new_embed\n```\n:::\n\n\n1. `align_corners` controls how the old and new grids are aligned during interpolation. `align_corners=True` treats pixels as discrete points and forces the points at the four corners of the old and new grids to align, so the values at the corner positions are preserved; `align_corners=False` treats pixels as small squares and aligns the outer boundary of the whole image rather than the centers of corner pixels. In this way, all positions are redistributed according to the overall scale, which is closer to the default behavior of ordinary image resizing.\n\nTest the length change:\n\n::: {#1a166124 .cell execution_count=9}\n``` {.python .cell-code}\n# First dimension must be 1 because it's a parameter,\n# not a batch of embeddings.\npos_embed = torch.randn(1, 14 * 14 + 1, 64)\nnew_pos_embed = interpolate_pos_embedding(\n    pos_embed,\n    old_grid_size=(14, 14),\n    new_grid_size=(24, 24),\n)\n\nprint('Old positional embedding shape:', pos_embed.shape)\nprint('New positional embedding shape:', new_pos_embed.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOld positional embedding shape: torch.Size([1, 197, 64])\nNew positional embedding shape: torch.Size([1, 577, 64])\n```\n:::\n:::\n\n\nWe can see that the original positional embedding length is 197 (196 patches + 1 class token), and the new positional embedding length is 577 (576 patches + 1 class token). In this way, it can adapt to inputs with different resolutions.\n\n## 11.3.8 Chapter Summary\n\nIn this section, we added two key designs in the ViT input module: **class token** and **position embedding**.\n\nPatch embedding can only turn an image into a patch token sequence:\n\n$$\n(B, C, H, W) \\rightarrow (B, N, D)\n$$\n\nBut image classification needs a representation of the whole image, so ViT adds a learnable class token at the beginning of the sequence:\n\n$$\n(B, N, D) \\rightarrow (B, N + 1, D)\n$$\n\nAfter the Transformer Encoder, the output representation of the class token is used as the representation of the whole image and fed into the classification head.\n\nAt the same time, because self-attention itself does not contain positional information, ViT also adds learnable positional embeddings to each token:\n\n$$\nZ = X + P\n$$\n\nIn this way, the model not only knows which patch content each token represents, but can also perceive where this patch is in the image through positional embedding.\n\nSo the construction process of the complete ViT input module is:\n\n$$\n\\text{image}\n\\rightarrow\n\\text{patch embedding}\n\\rightarrow\n\\text{class token}\n\\rightarrow\n\\text{positional embedding}\n$$\n\nAt this point, we have completed the construction of the ViT input module. In the next section, we will move into the implementation of the ViT Encoder and use self-attention to fuse information from patch tokens and the class token, obtaining a representation of the whole image.\n\n",
    "supporting": [
      "ch11.3-positional-embedding_files"
    ],
    "filters": [],
    "includes": {}
  }
}