import dnnlpy.nn as dnn
import dnnlpy.nn.functional as dF


def test_nn_exports_new_modules():
    for name in [
        'BatchNorm1d',
        'BatchNorm2d',
        'BatchNorm3d',
        'CELU',
        'CrossEntropyLoss',
        'Dropout',
        'Dropout1d',
        'Dropout2d',
        'Dropout3d',
        'ELU',
        'GELU',
        'GroupNorm',
        'HardShrink',
        'HardSigmoid',
        'HardSwish',
        'HardTanh',
        'Identity',
        'InstanceNorm1d',
        'InstanceNorm2d',
        'InstanceNorm3d',
        'LayerNorm',
        'LeakyReLU',
        'Linear',
        'LocalResponseNorm',
        'LogSigmoid',
        'LogSoftmax',
        'Mish',
        'PReLU',
        'RMSNorm',
        'ReLU',
        'ReLU6',
        'RReLU',
        'SELU',
        'SiLU',
        'Sigmoid',
        'SoftShrink',
        'SoftSign',
        'Softmax',
        'Softmin',
        'Softplus',
        'Tanh',
        'TanhShrink',
        'Threshold',
    ]:
        assert hasattr(dnn, name)


def test_functional_exports_new_functions():
    for name in [
        'batch_norm',
        'celu',
        'cross_entropy',
        'dropout',
        'dropout1d',
        'dropout2d',
        'dropout3d',
        'elu',
        'gelu',
        'generate_causal_mask',
        'group_norm',
        'hardsigmoid',
        'hardshrink',
        'hardswish',
        'hardtanh',
        'instance_norm',
        'layer_norm',
        'leaky_relu',
        'linear',
        'local_response_norm',
        'log_softmax',
        'logsigmoid',
        'mish',
        'multi_head_attention',
        'naive_attention',
        'prelu',
        'relu',
        'relu6',
        'rms_norm',
        'rrelu',
        'scaled_dot_product_attention',
        'selu',
        'sigmoid',
        'silu',
        'softmax',
        'softmin',
        'softplus',
        'softshrink',
        'softsign',
        'tanh',
        'tanhshrink',
        'threshold',
    ]:
        assert hasattr(dF, name)
