{
  "hash": "1114893d3dc295649f7abae3b3a22940",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nauthor: jshn9515\ndate: 2026-05-13\ndate-modified: 2026-05-13\nopen-graph:\n  title: ch11.3-positional-embedding\n  description: \"11.3 Class Token and Positional Embedding: Representing the Whole Image\"\ntitle: \"11.3 Class Token 与 Positional Embedding：让序列表示整张图\"\norder: 3\n---\n\n上一节里，我们已经把图像从原始张量\n\n$$\n(B, C, H, W)\n$$\n\n转换成了 patch token 序列：\n\n$$\n(B, N, D)\n$$\n\n其中 $N$ 是 patch 数量，$D$ 是每个 token 的 embedding 维度。\n\n到这一步，图像已经可以被看成一串视觉 token，并且可以送入 Transformer Encoder。但是，这还不是 ViT 的完整输入。\n\n原因有两个。\n\n第一个问题是：如果要做图像分类，最后应该用哪个 token 表示整张图？Patch token 本身表示的是局部图像块，而分类任务需要的是整张图像的语义表示。\n\n第二个问题是：Transformer 本身并不知道每个 patch 来自图像的哪个位置。Patch embedding 把图像切成序列以后，如果不额外加入位置信息，模型很难区分一个 patch 是来自左上角，还是来自右下角。\n\n所以，在把 patch token 送入 Transformer Encoder 之前，ViT 还会做两件事：\n\n1. 在序列最前面加入一个 **class token**，用来汇聚整张图的信息；\n2. 给每个 token 加上 **positional embedding**，用来告诉模型 token 的位置信息。\n\n这一节我们就来讨论这两个设计。\n\n::: {#5d764df0 .cell execution_count=2}\n``` {.python .cell-code}\nimport dnnl.models.vit as vit\nimport torch\nimport torch.nn as nn\nimport torch.nn.functional as F\nfrom torch import Tensor\n\nprint('PyTorch version:', torch.__version__)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPyTorch version: 2.12.0+xpu\n```\n:::\n:::\n\n\n## 11.3.1 Patch Token 还不能直接表示整张图\n\n经过 patch embedding 以后，一张图像会变成一个 patch 序列：\n\n$$\nX = [x_1, x_2, \\dots, x_N]\n$$\n\n其中每个 $x_i \\in \\mathbb{R}^D$ 表示一个图像 patch。\n\n如果后面接的是 Transformer Encoder，那么输出仍然是一个序列：\n\n$$\nH = [h_1, h_2, \\dots, h_N]\n$$\n\n这里每个 $h_i$ 都是对应 patch 的上下文表示。它不再只包含第 $i$ 个 patch 自己的信息，而是通过 self-attention 融合了其他 patch 的信息。\n\n但对于图像分类来说，我们最后需要的是一个整张图像的向量表示，而不是 $N$ 个 patch 向量。也就是说，我们需要从 `(B, N, D)` 的输出中得到一个 `(B, D)` 的图像表示。\n\n一个很自然的做法是对所有 patch token 做平均池化：\n\n$$\nh_\\mathrm{avg} = \\frac{1}{N}\\sum_{i=1}^N h_i\n$$\n\n这当然是可行的。事实上，很多后来的视觉 Transformer 变体也会使用平均池化或者类似的聚合方式。\n\n但原始 ViT 采用的是另一种设计：在 patch token 前面加入一个特殊的可学习 token，叫做 **class token**，也常写作 `[CLS]`。\n\n## 11.3.2 Class Token：让一个 Token 代表整张图\n\nClass token 的想法来自 BERT 这类 Transformer 模型。在文本分类中，模型会在输入序列前面加入一个特殊 token，例如 `[CLS]`。经过 Transformer 编码以后，这个 token 的输出表示会被用作整个序列的表示。ViT 借用了这个思路。\n\n假设 patch token 序列是：\n\n$$\n[x_1, x_2, \\dots, x_N]\n$$\n\nViT 会在它前面加一个可学习向量 $x_\\mathrm{cls}$：\n\n$$\nX = [x_\\mathrm{cls}, x_1, x_2, \\dots, x_N]\n$$\n\n这样，序列长度就从 $N$ 变成了 $N + 1$。\n\n这个 class token 一开始只是一个普通的可学习参数。它本身不对应图像中的某个 patch，也不来自输入图像。它的作用是在 Transformer Encoder 中和所有 patch token 进行 self-attention 交互。\n\n经过多层 Transformer Encoder 以后，class token 的输出表示可以看作整张图像的信息汇聚结果：\n\n$$\nh_\\mathrm{cls} = H[:, 0, :]\n$$\n\n然后把这个向量送入分类头，就可以得到图像分类 logits：\n\n$$\n\\mathrm{logits} = h_\\mathrm{cls} W + b\n$$\n\n直观来说，class token 就像是一个全局位置。它不代表某个局部图像块，而是专门用来从所有 patch token 中收集信息，最后形成整张图像的表示。\n\n## 11.3.3 Class Token 的 PyTorch 实现\n\n在实现上，class token 通常是一个形状为 `(1, 1, embed_dim)` 的可学习参数：\n\n::: {#74e36056 .cell execution_count=3}\n``` {.python .cell-code}\nclass ViTAddClassToken(nn.Module):\n    def __init__(self, embed_dim: int):\n        super().__init__()\n        cls_token = torch.zeros(1, 1, embed_dim)\n        self.cls_token = nn.Parameter(cls_token)\n        nn.init.trunc_normal_(self.cls_token, std=0.02)\n\n    def forward(self, x: Tensor) -> Tensor:\n        batch_size = x.size(0)\n        cls_token = self.cls_token.expand(batch_size, -1, -1)\n        x = torch.concat([cls_token, x], dim=1)\n        return x\n```\n:::\n\n\n这里有两个细节值得注意。\n\n第一个细节是 `cls_token` 的形状是 `(1, 1, D)`，而不是 `(B, 1, D)`。因为它是模型参数，不应该为每个 batch 单独存一份。真正前向传播时，我们再用 `expand` 把它扩展到当前 batch size：\n\n```python\ncls_token = self.cls_token.expand(batch_size, -1, -1)\n```\n\n第二个细节是 `expand` 不会真正复制参数数据，它只是创建一个广播后的视图。这样所有样本使用的是同一个可学习 class token，但在计算图中会根据 batch 中所有样本的梯度一起更新它。\n\n我们测试一下形状变化：\n\n::: {#bf7f96f0 .cell execution_count=4}\n``` {.python .cell-code}\nbatch_size = 2\nnum_patches = 16\nembed_dim = 64\n\nx = torch.randn(batch_size, num_patches, embed_dim)\ncls_layer = ViTAddClassToken(embed_dim)\nout = cls_layer(x)\n\nprint('Input shape:', x.shape)\nprint('Output shape:', out.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nInput shape: torch.Size([2, 16, 64])\nOutput shape: torch.Size([2, 17, 64])\n```\n:::\n:::\n\n\n输入形状是 `(B, N, D)`，输出形状变成 `(B, N + 1, D)`。多出来的第一个 token 就是 class token。\n\n## 11.3.4 为什么还需要 Positional Embedding？\n\n加入 class token 以后，序列已经可以表示整张图了。但还有一个更基础的问题：patch token 的位置信息在哪里？\n\nPatch embedding 得到的是一串向量：\n\n$$\n[x_1, x_2, \\dots, x_N]\n$$\n\n虽然我们在展开 patch 时通常会按照从左到右、从上到下的顺序排列，但 self-attention 本身并不会天然理解这个顺序的含义。\n\n这一点和文本 Transformer 中的问题是一样的。Self-attention 在计算时主要看 token 向量之间的相似度。如果没有额外的位置信息，它并不知道某个 token 是第一个位置还是第十个位置。\n\n对于图像来说，位置甚至更加重要。一个 patch 在左上角和在右下角，语义可能完全不同。比如天空通常在图像上方，草地通常在图像下方；人脸中的眼睛、鼻子、嘴也有相对稳定的空间关系。如果模型完全不知道 patch 的位置，就很难利用这些空间结构。\n\n因此，ViT 会给每个 token 加上一个可学习的位置向量：\n\n$$\nZ = X + P\n$$\n\n其中，$X \\in \\mathbb{R}^{B \\times (N+1) \\times D}$ 是加入 class token 之后的序列，$P \\in \\mathbb{R}^{1 \\times (N+1) \\times D}$ 是 position embedding。\n\n注意这里的位置数量是 $N + 1$，因为除了 $N$ 个 patch token 之外，class token 也需要一个自己的位置 embedding。\n\n## 11.3.5 Positional Embedding 的 PyTorch 实现\n\n原始 ViT 使用的是可学习的绝对位置嵌入。也就是说，模型会直接学习一个参数矩阵：\n\n$$\nP = [p_\\mathrm{cls}, p_1, p_2, \\dots, p_N]\n$$\n\n其中 $p_\\mathrm{cls}$ 是 class token 的位置嵌入，$p_i$ 是第 $i$ 个 patch 位置的位置嵌入。\n\n然后把它加到 token embedding 上：\n\n$$\nZ = X + P\n$$\n\n实现起来非常简单：\n\n::: {#bd248395 .cell execution_count=5}\n``` {.python .cell-code}\nclass ViTPositionalEmbedding(nn.Module):\n    def __init__(\n        self,\n        num_patches: int,\n        embed_dim: int,\n        use_cls_token: bool = True,\n    ):\n        super().__init__()\n        self.num_patches = num_patches\n        self.embed_dim = embed_dim\n        self.use_cls_token = use_cls_token\n\n        num_tokens = num_patches + int(use_cls_token)\n        pos_embed = torch.zeros(1, num_tokens, embed_dim)\n        self.pos_embed = nn.Parameter(pos_embed)\n        nn.init.trunc_normal_(self.pos_embed, std=0.02)\n\n    def forward(self, x: Tensor) -> Tensor:\n        if x.size(1) != self.pos_embed.size(1):\n            raise AssertionError(\n                f'Expected sequence length {self.pos_embed.size(1)}, '\n                f'but got {x.size(1)}.'\n            )\n        return x + self.pos_embed\n```\n:::\n\n\n测试一下：\n\n::: {#17ea8324 .cell execution_count=6}\n``` {.python .cell-code}\nnum_patches = 16\nembed_dim = 64\n\nx = torch.randn(2, num_patches, embed_dim)\nx = ViTAddClassToken(embed_dim)(x)\npos_embed = ViTPositionalEmbedding(\n    num_patches=num_patches,\n    embed_dim=embed_dim,\n    use_cls_token=True,\n)\nout = pos_embed(x)\n\nprint('After class token:', x.shape)\nprint('After positional embedding:', out.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAfter class token: torch.Size([2, 17, 64])\nAfter positional embedding: torch.Size([2, 17, 64])\n```\n:::\n:::\n\n\n可以看到，加入 positional embedding 不会改变张量形状。它只是给每个 token 的表示加上一个和位置有关的偏移量。\n\n也就是说：\n\n$$\n(B, N+1, D) \\rightarrow (B, N+1, D)\n$$\n\n维度没有变化，但 token 表示中已经包含了位置信息。\n\n## 11.3.6 Class Token 和 Positional Embedding 的顺序\n\n在 ViT 里，常见的输入构造顺序是：\n\n$$\n\\text{image} \\rightarrow\n\\text{patch embedding} \\rightarrow\n\\text{append class token} \\rightarrow\n\\text{add positional embedding}\n$$\n\n也就是：\n\n$$\n(B, C, H, W) \\rightarrow\n(B, N, D) \\rightarrow\n(B, N+1, D) \\rightarrow\n(B, N+1, D)\n$$\n\n为什么通常是先加 class token，再加 positional embedding？\n\n因为 positional embedding 需要和最终输入序列中的每个 token 一一对应。如果先给 patch token 加位置，再拼接 class token，那么 class token 还需要单独处理自己的位置嵌入。先把 class token 拼进去，再统一加一个长度为 $N+1$ 的 position embedding，会更直接。\n\n<figure class=\"figure\" style=\"text-align: center;\">\n  <img src=\"figures/ch11.4-vit.png\" style=\"width: 70%;\" />\n  <figcaption>图 1：ViT 模型结构 [@dosovitskiy2021ViT]</figcaption>\n</figure>\n\n下面我们把上一节的 patch embedding 和这一节讲的 class token、positional embedding 合在一起，得到一个完整的 ViT 输入模块。\n\n::: {#d5d7e640 .cell execution_count=7}\n``` {.python .cell-code}\nclass ViTEmbedding(nn.Module):\n    def __init__(\n        self,\n        image_size: int = 224,\n        patch_size: int = 16,\n        in_channels: int = 3,\n        embed_dim: int = 768,\n        dropout: float = 0.0,\n    ):\n        super().__init__()\n        self.patch_embed = vit.ViTConvPatchEmbedding(\n            image_size=image_size,\n            patch_size=patch_size,\n            in_channels=in_channels,\n            embed_dim=embed_dim,\n        )\n        self.add_cls_token = ViTAddClassToken(embed_dim)\n        self.pos_embed = ViTPositionalEmbedding(\n            num_patches=self.patch_embed.num_patches,\n            embed_dim=embed_dim,\n            use_cls_token=True,\n        )\n        self.dropout = nn.Dropout(dropout)\n\n    def forward(self, x: Tensor) -> Tensor:\n        x = self.patch_embed(x)\n        x = self.add_cls_token(x)\n        x = self.pos_embed(x)\n        x = self.dropout(x)\n        return x\n```\n:::\n\n\n测试一下形状：\n\n::: {#a99ccb28 .cell execution_count=8}\n``` {.python .cell-code}\nvit_embed = ViTEmbedding(\n    image_size=32,\n    patch_size=8,\n    in_channels=3,\n    embed_dim=64,\n)\n\nx = torch.randn(2, 3, 32, 32)\nout = vit_embed(x)\n\nprint('ViT embedding output shape:', out.shape)\nprint('Number of patch tokens:', vit_embed.patch_embed.num_patches)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nViT embedding output shape: torch.Size([2, 17, 64])\nNumber of patch tokens: 16\n```\n:::\n:::\n\n\n这里图像大小是 $32 \\times 32$，patch size 是 $8 \\times 8$，所以每张图像有 16 个 patch token。加上 class token 后，序列长度变成 17。因此输出形状是 `(B, 17, D)`。\n\n## 11.3.7 Positional Embedding 和二维空间结构\n\n到这里，可能大家还有一个容易疑惑的地方：\n\n> **图像原本是二维网格，但 ViT 的 positional embedding 看起来是一维的。这样会不会丢失二维空间结构？**\n\n答案是不会。虽然 ViT 使用的是一维 position embedding，但这并不意味着它完全丢掉了图像的二维位置信息。因为 patch 序列是按照固定顺序从二维网格展平得到的。\n\n比如一个 $14 \\times 14$ 的 patch 网格，会按照行优先顺序展平成 196 个 patch token。这样一来，序列中的第 $i$ 个位置就总是对应原图中的某一个固定 patch 坐标。因此，position embedding 的形状虽然是 $(1, N+1, D)$，看起来只是在给一维序列加位置向量，但每个位置向量背后其实都对应着一个二维 patch 位置。\n\n不过，这种可学习绝对位置嵌入也有一个限制：它和训练时的 patch 网格大小绑定得比较紧。比如模型训练时使用 $224 \\times 224$ 图像和 $16 \\times 16$ patch，那么 patch 网格是 $14 \\times 14$，位置嵌入长度是 197；如果推理时换成更高分辨率的图像，例如 $384 \\times 384$，patch 网格就变成 $24 \\times 24$，位置嵌入长度就变成 577。这时原来的 positional embedding 长度就对不上了。\n\n那该怎么办呢？\n\n一个常见做法是对 patch 部分的 positional embedding 做二维插值。Class token 的位置嵌入单独保留，patch positional embedding 先还原成二维网格，再插值到新的网格大小，最后重新展平成序列。\n\n具体做法是：\n\n1. 从 positional embedding 中分离出 class token 的位置嵌入和 patch token 的位置嵌入。\n2. 把 patch token 的位置嵌入 reshape 成二维网格的形状 `(1, old_h, old_w, D)`。\n3. 使用双线性插值把位置嵌入从旧的网格大小插值到新的网格大小 `(1, new_h, new_w, D)`。\n4. 把插值后的 patch 位置嵌入 reshape 回序列形状 `(1, new_h * new_w, D)`。\n5. 把 class token 的位置嵌入和新的 patch 位置嵌入拼接起来，得到新的 positional embedding。\n\n下面是一个简化版实现：\n\n::: {#1b62a6c0 .cell execution_count=9}\n``` {.python .cell-code}\ndef interpolate_pos_embedding(\n    pos_embed: Tensor,\n    old_grid_size: tuple[int, int],\n    new_grid_size: tuple[int, int],\n) -> Tensor:\n    cls_pos_embed = pos_embed[:, :1]\n    patch_pos_embed = pos_embed[:, 1:]\n\n    old_h, old_w = old_grid_size\n    new_h, new_w = new_grid_size\n    embed_dim = pos_embed.size(-1)\n\n    patch_pos_embed = patch_pos_embed.reshape(1, old_h, old_w, embed_dim)\n    patch_pos_embed = patch_pos_embed.permute(0, 3, 1, 2)\n    patch_pos_embed = F.interpolate(\n        patch_pos_embed,\n        size=(new_h, new_w),\n        mode='bicubic',\n        align_corners=False,  # <1>\n    )\n    patch_pos_embed = patch_pos_embed.permute(0, 2, 3, 1)\n    patch_pos_embed = patch_pos_embed.reshape(1, new_h * new_w, embed_dim)\n\n    new_embed = torch.concat([cls_pos_embed, patch_pos_embed], dim=1)\n    return new_embed\n```\n:::\n\n\n1. `align_corners` 控制插值时新旧网格的对齐方式。`align_corners=True` 把像素看成离散的点，并强行对齐新旧网格四个角上的点，因此角落位置的值会被保留；`align_corners=False` 则把像素看成一个个小方格，对齐的是整张图像的外围边界，而不是角落像素的中心。这样所有位置会按整体比例重新分布，更接近普通图像缩放的默认行为。\n\n测试一下长度变化：\n\n::: {#4eb498fd .cell execution_count=10}\n``` {.python .cell-code}\n# First dimension must be 1 because it's a parameter,\n# not a batch of embeddings.\npos_embed = torch.randn(1, 14 * 14 + 1, 64)\nnew_pos_embed = interpolate_pos_embedding(\n    pos_embed,\n    old_grid_size=(14, 14),\n    new_grid_size=(24, 24),\n)\n\nprint('Old positional embedding shape:', pos_embed.shape)\nprint('New positional embedding shape:', new_pos_embed.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOld positional embedding shape: torch.Size([1, 197, 64])\nNew positional embedding shape: torch.Size([1, 577, 64])\n```\n:::\n:::\n\n\n可以看到，原来的 positional embedding 长度是 197（196 个 patch + 1 个 class token），新的 positional embedding 长度是 577（576 个 patch + 1 个 class token）。这样就可以适应不同分辨率的输入了。\n\n## 11.3.8 本章小结\n\n这一节我们补上了 ViT 输入模块中的两个关键设计：class token 和 position embedding。\n\nPatch embedding 只能把图像变成 patch token 序列：\n\n$$\n(B, C, H, W) \\rightarrow (B, N, D)\n$$\n\n但图像分类需要一个整张图像的表示，所以 ViT 会在序列前面加入一个可学习的 class token：\n\n$$\n(B, N, D) \\rightarrow (B, N + 1, D)\n$$\n\n经过 Transformer Encoder 后，class token 的输出表示会被用作整张图像的表示，并送入分类头。\n\n同时，由于 self-attention 本身不包含位置信息，ViT 还会给每个 token 加上可学习的位置嵌入：\n\n$$\nZ = X + P\n$$\n\n这样，模型不仅知道每个 token 表示哪个 patch 的内容，也能通过 positional embedding 感知这个 patch 在图像中的位置。\n\n到这里，ViT 的输入已经准备好了：\n\n$$\n\\text{image} \\rightarrow\n\\text{patch embedding} \\rightarrow\n\\text{class token} \\rightarrow\n\\text{positional embedding}\n$$\n\n到这里，我们就完成了 ViT 输入模块的构建。下一节我们将进入 Transformer Encoder 的实现，看看 ViT 是如何通过 self-attention 来融合 patch token 和 class token 的信息，从而得到整张图像的表示的。\n\n",
    "supporting": [
      "ch11.3-positional-embedding_files\\figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}