---
config:
  theme: base
  htmlLabels: false
  fontFamily: "Arial, Microsoft YaHei, sans-serif"
  themeVariables:
    fontSize: "18px"
    primaryColor: "#e9f2fc"
    primaryBorderColor: "#296bb7"
    primaryTextColor: "#333333"
    lineColor: "#0b0b0b"

  flowchart:
    wrappingWidth: 250

  themeCSS: |
    .node text,
    .nodeLabel,
    .label text {
      font-weight: 400;
      font-style: normal;
    }
    .node rect,
    .flowchart-link {
      stroke-width: 1px;
    }
---

flowchart TD
    X[Input]

    X --> LN1[LayerNorm]
    LN1 --> MSA[Multihead Self-Attention]
    MSA --> ADD1((+))

    X -. Residual .-> ADD1

    ADD1 --> H[Hidden H]

    H --> LN2[LayerNorm]
    LN2 --> MLP[MLP]
    MLP --> ADD2((+))

    H -. Residual .-> ADD2

    ADD2 --> OUT[Output]
