---
config:
  theme: base
  htmlLabels: false
  fontFamily: "Arial, Microsoft YaHei, sans-serif"
  themeVariables:
    fontSize: "18px"
    primaryColor: "#e9f2fc"
    primaryBorderColor: "#296bb7"
    primaryTextColor: "#333333"
    lineColor: "#0b0b0b"

  themeCSS: |
    .node text,
    .nodeLabel,
    .label text {
      font-weight: 400;
      font-style: normal;
    }
    .node rect,
    .flowchart-link {
      stroke-width: 1px;
    }
---

flowchart TD
    X[Input]

    X --> MHA[Multi-Head Self-Attention]
    X --> Skip1[Identity]

    MHA --> Add1((+))
    Skip1 --> Add1

    Add1 --> LN1[LayerNorm]

    LN1 --> FFN[Feed-Forward Network]
    LN1 --> Skip2[Identity]

    FFN --> Add2((+))
    Skip2 --> Add2

    Add2 --> LN2[LayerNorm]
    LN2 --> Y[Output]
